name: Python package

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 167.71.36.226
          username: root
          password: ${{ secrets.PASSWORD }}
          port: 22
          scripts: |
            cd /home/microservices_devops
            source ./venv/bin/activate
            git pull
            pip install -r requirements.txt 
            supervisorctl restart insertservice
            supervisorctl restart deadlineservice
            supervisorctl restart notifyservice
      - name: Run tests and collect coverage
        run: |
          pytest -s
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
